version: "3.3"
services:
  flask:
    build: .
    links:
      - db
    env_file: 
      - .env
    ports:
      - 5000:5000
  db:
    image: postgres:13.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  adminer:
    image: michalhosna/adminer:4.7.7-en_v1
    environment:
      ADMINER_DRIVER: pgsql
      ADMINER_SERVER: ${DB_HOST} 
      ADMINER_USERNAME: ${DB_USER}
      ADMINER_PASSWORD: ${DB_PASSWORD}
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: ${DB_NAME}
    logging:
      driver: "none"
    links:
      - db
    ports:
      - 5050:8080

volumes:
  db_data: