version: "3.3"
services:
  flask:
    volumes:
      - ./psan:/srv/psan
      - ./instance:/srv/instance
      - ./config:/srv/config
      - ./tests:/srv/tests
    environment:
      DB_NAME: ${DB_NAME:-psan_db_test}
    command: ["wait-for-it", "db:5432", "--", "/srv/run_tests.sh"]
  db:
    environment:
      POSTGRES_DB: ${DB_NAME:-psan_db_test}
    volumes:
      - db_tmp:/var/lib/postgresql/data
    container_name: "db-test"
  redis:
    logging:
      driver: "none" # Don't log anything
volumes:
  db_tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs