version: "3.3"
services:
  flask:
    build: .
    depends_on:
      - db
      - redis
    environment: 
      DB_HOST: db
      DB_NAME: ${DB_NAME:-psan_db}
      CELERY_REDIS: redis://redis:6379
    env_file: 
      - .env
    ports:
      - 5000:5000
  db:
    image: postgres:13.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${DB_NAME:-psan_db}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  redis:
    image: redis:6.0.14-alpine

volumes:
  db_data: